language: csharp
solution: Aaru.sln
mono:
 - latest
notifications:
  irc:
    channels:
      - "chat.freenode.net#Aaru"
    skip_join: true
    template:
      - "Commit %{commit} by %{author} in %{branch} %{result} after %{duration}."
      - "Commit changes: %{commit_subject}"
      - "Details on %{build_url}, changes on %{compare_url}"
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe restore Aaru.sln
