name: Image Bug Report
description: Bugs report on commands that handle images, like converting or extracting.
labels: ["bug", "needs triage", "dump image format"]
assignees:
  - silaslaspada
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Aaru are you running?
      options:
        - 5.3.0
        - 5.2.0
        - Older
        - 6.0.0-alpha6
        - Development commit
    validations:
      required: true
  - type: input
    id: commit
    attributes:
      label: Commit hash
      description: If using a developmen commit, which one
  - type: checkboxes
    id: debug
    attributes:
      label: Tested debug version?
      description: Have you reproduced the problem using the debug version?
      options:
        - label: "Yes"
          required: true
  - type: checkboxes
    id: os
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: Windows
          required: true
        - label: Linux
          required: true
        - label: macOS
          required: true
        - label: Other
          required: true
  - type: checkboxes
    id: bitsize
    attributes:
      label: What is the architectural bit size you're using?
      description: You may select more than one.
      options:
        - label: 32-bit
        - label: 64-bit
        - label: Unsure or unknown
  - type: checkboxes
    id: cpu
    attributes:
      label: What processor are you using?
      description: You may select more than one.
      options:
        - label: An Intel or AMD
        - label: An ARM or Apple Silicon
        - label: Unsure or unknown
  - type: input
    id: format
    attributes:
      label: Image format
    validations:
      required: true
  - type: input
    id: application
    attributes:
      label: Application that created the image
    validations:
      required: true
  - type: checkboxes
    id: action
    attributes:
      label: What were you doing when it failed?
      description: Choose all that apply
      options:
        - label: I was converting the image to another format...
        - label: I was retrieving image information...
        - label: I was retrieving filesystem information...
        - label: I was listing the filesystem contents...
        - label: I was extracting the filesystem contents...
        - label: I was creating a metadata sidecar...
        - label: I was checksumming the image...
        - label: I was verifying the image...
        - label: I was calculating the image entropy...
  - type: input
    id: target_format
    attributes:
      label: Destination image format
      description: If you were converting the image format, what format were you trying to convert it into
  - type: input
    id: filesystem
    attributes:
      label: Filesystem
      description: If you were listing information, contents, or extracting the contents of a filesystem, which filesystem is it? (leave empty if unknown)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the bug
    validations:
      required: true
  - type: input
    id: command_line
    attributes:
      label: Exact command line used
      placeholder: "`Aaru [command] [parameters]`"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Output of command execution with debug output enabled
      placeholder: Paste the whole output of the executed command when you append '-d' to your command line parameters here
      render: shell
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Affected image
      placeholder: Upload the image, compressed and with the number of this issue.
                   If the image contains personal data contact the project lead, and the image contents will be handled confidentially under the GDPR requirements.
