name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
    - name: Restore dependencies
      run: dotnet restore Aaru.sln
    - name: Build
      run: dotnet build --no-restore Aaru.sln
